#!/usr/bin/env bash
# 20221025 WF
#  used 01_collect.R's `d_rank %>% arrange(overall)` to pull out best 50-trial blocks
#  modified afni_to_task.R s.t. left/rigth are replaced with good/nogood 
#  saving to edn here to load in clojurescript and set left/right, step, and prob there
seeds=(23040 28469 7437 6471 1740 9555 23711 1936 22679)
filepath=out/200.34s/v1.5-nocatch-qwalk_50_
outcljs=../src/landscape/mr_times.cljs

for seed in "${seeds[@]}"; do
   ./afni_to_task.R --goodnogood "$filepath$seed/events.txt"|
      sed "1s/^/:seed_$seed /"
done | 
   sed '1s/^/(ns landscape.mr-times "generated by mk_edn_goodnogood.bash")(def mr-times {/;$s/$/})/' > $outcljs 
warn "# wrote $outcljs"
